//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace apiMobileDevelope.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warehouse
    {
        public int Code_Product { get; set; }
        public string Name_Product { get; set; }
        public string Type_Product { get; set; }
        public int Count_Product { get; set; }
        public int Price_Product { get; set; }
       // public byte[] Photo_Product { get; set; }
    }
}
